### ISSUE TITLE
Classes and functions without valid component prefix

### ISSUE THREAD

**Issue by mudrd8mz** [bozoh/moodle-block_simple_certificate#1]
The class `simple_certificate_tree` violates the naming conventions - see https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace-collisions

Better to use Moodle class autoloading mechanism that would implicitly "force" you to name the class correctly.

**Comment by bozoh** [comment]
this code is a copy from private_files block,  so it's out of convention there too

**Comment by mudrd8mz** [comment]
Thanks Carlos for raising the issue in the Private files block. I reported that as a Moodle bug in https://tracker.moodle.org/browse/MDL-52356
