### ISSUE TITLE
List certificates for any users

### ISSUE THREAD

**Issue by davidherney** [bozoh/moodle-block_simple_certificate#3]
Hi...

In view.php, the user id is not validated and it is a request parameter. A user can get the certificate list for any other user changing the uid param by get.
`$uid = required_param('uid', PARAM_INT);`

It is a bug or a feature?
In the block content, the userid is from the session user.
`$certs = self::get_issued_certificates($USER->id, $COURSE->id);`

Besides, in mod/simplecertificate/wmsendfile.php the user is validated and the _certificatecopy_ marker is added when the current user is different to the certificate user, however, the personal information is into the certificate. A user can get many certificates changing values into the URL, including guest users.

Can I change this and submit the correction? or 
Do you want to keep it that way?

Saludos

**Comment by bozoh** [comment]
in block,  it's should  list only user's certificates

And in certificate,  wmsendfile.php   it's  part of  verify.php, which  verify if it's a valid certificate, and any one can do that including guest, but if it is a guest(or other user) a mark is added.

I know that some user can list all certificates by changing the certificate code, and i think this can be discussed if guest, or others users, can get the certificate file with a copy mark or not

**Comment by davidherney** [comment]
Hi bozoh ...

A user can list his certificates or the certificates from the other people if he use the file **blocks/simple_certificate/view.php**, the file is into the block and it not check the current user, the user id is a requested parameter.

**mod/simplecertificate/wmsendfile.php** is an open file and a robot can send multiple ids in the URL parameters in order to get a lot of certificates or something like that, without a code, only a number. It can be used a URL token-key in order to protect the information.

Please, consider this annotations :). If you like, I can add something to change it.

Saludos

**Comment by bozoh** [comment]
you are right ,  wmsendfile  uses  issued certificate id   not the code, as i can remember wmsendfile it's  used by moodle API to send file,  i must check it  because it's a threat

in view.php  it should use USER->id  ,  but  i can't  remember why it's not using, a threat too

Thanks to show me this

**Comment by bozoh** [comment]
Well, i change the code and tests still passed,  so  i think  there is "no why"  to be like that
i fixed in this commit
https://github.com/bozoh/moodle-block_simple_certificate/commit/fa33690c1932daf4629f76e2bef7918895380753

I put wrong issue reference :-1: 

Thanks for help
