### ISSUE TITLE
Upgrade throw errors

### ISSUE THREAD

**Issue by demontech** [bozoh/moodle-block_simple_certificate#4]
Hi Carlos,

The block was working really well, but now that I install the new upgrade in M3.1 I got the following errors when I click on an issued certificate from the block.

![image](https://user-images.githubusercontent.com/8148238/30677664-eae250a0-9e41-11e7-85ea-1fc891b2a889.png)

and I'm using the latest version of mod simple certificate 2.2.6 (2017091800)

Thanks!

**Comment by bozoh** [comment]
oppps, my  bad, i will fix it

**Comment by bozoh** [comment]
I have add a test to avoid this happen again

**Comment by demontech** [comment]
Yes, I can confirm. I tested and it's working fine.

Thanks Carlos!
